/*!
\file src/build.h
\brief Build number file.
This file is automatically generated by ./make_build_svn.sh in build time from
a last SVN revision number in directory tree.
WARNING! All changes made here will be lost.
*/
#ifndef CZ_BUILD_H
#define CZ_BUILD_H

/* WARNING! Cannot detect SVN revision number. */

#endif//CZ_BUILD_H
